/**
 * School-wide facts. Edit here and every page, footer, and search-engine tag updates.
 * Keep wording plain. No em-dashes, no exclamation marks (see design.md).
 */
export const site = {
  name: 'Mercer Med Tech',
  legalName: 'Mercer Med Tech, Inc.',
  shortName: 'MMT',
  url: 'https://www.mercermedtech.com',
  positioningLine: 'Med and Tech. Two paths to a better job.',
  phone: { display: '(609) 712-5499', href: 'tel:+16097125499', e164: '+1-609-712-5499' },
  email: 'mercermedtech@gmail.com',
  address: {
    street: '168 Franklin Corner Rd, Bldg 2, Suite #140',
    city: 'Lawrenceville',
    region: 'NJ',
    postalCode: '08648',
    country: 'US',
    mapsUrl:
      'https://www.google.com/maps/search/?api=1&query=168%20Franklin%20Corner%20Rd%2C%20Bldg%202%2C%20Suite%20140%2C%20Lawrenceville%2C%20NJ%2008648',
  },
  geo: { latitude: 40.2937, longitude: -74.7429 },
  social: {
    facebook: 'https://www.facebook.com/mercermedtech',
    instagram: 'https://www.instagram.com/mercermedtech/',
  },
  credentialFinderUrl:
    'https://credentialfinder.org/detail/organization/ce-b96e30d0-ddd5-48c7-94e7-2d1e99ed1549',
  licensingLine:
    'Mercer Med Tech is a state-approved private vocational school licensed by the New Jersey Department of Labor and Workforce Development.',
  /**
   * The same statement with the Eligible Training Provider List added. Used in
   * both footers. Say ETPL about the school, never about a single program.
   */
  licensingEtplLine:
    "Mercer Med Tech is a state-approved private vocational school licensed by the New Jersey Department of Labor and Workforce Development, and is on New Jersey's Eligible Training Provider List (ETPL).",
  /** Eligible Training Provider List, on its own. */
  etplLine: "Mercer Med Tech is on New Jersey's Eligible Training Provider List (ETPL).",
  /** No days or times anywhere. This exact sentence replaces every schedule. */
  infoSessionsNote: 'Details on upcoming information sessions will be shared soon.',
  /** Shown as the copyright line in both footers. */
  copyright: '© 2026 Mercer Med Tech. All rights reserved.',
  /**
   * Images with an address that never changes, for everything outside the site
   * that keeps a copy of it: the social card, the JSON-LD, and the
   * /images/logo-modern.png path the old static site published. Astro
   * fingerprints what it optimizes, which is right for the page and wrong here,
   * so these live in public/ and are generated by
   * scripts/make-static-images.mjs.
   */
  staticImages: {
    /** 1200x630 social card: the lockup on white over the Med-to-Tech rule. */
    ogCard: '/og-image.png',
    /** 600px wide logo, the address the old JSON-LD and social cards used. */
    logo: '/images/logo-modern.png',
  },
} as const;

/** Digital Literacy Training facts. The funding sentence is required by NJDOL and must stay word for word. */
export const dlt = {
  name: 'Digital Literacy Training',
  path: '/digital-literacy/',
  fundingSentence:
    'The funding for this initiative is being provided by the New Jersey Department of Labor and Workforce Development.',
  counties: ['Hunterdon', 'Middlesex', 'Monmouth', 'Mercer', 'Ocean', 'Somerset', 'Union'],
  countiesSentence:
    'Hunterdon, Middlesex, Monmouth, Mercer, Ocean, Somerset, or Union county',
  length: 'About 5 to 6 weeks',
  languages: ['English', 'Spanish'],
  /** Not "now enrolling". See the owner decisions of 2026-09-18. */
  enrollmentLabel: 'Enrolling soon',
} as const;

/** The two tracks. Order rule: Med first and on the left, Tech second and on the right. */
export const tracks = {
  med: { id: 'med', label: 'Med', title: 'Allied health certification', anchor: 'programs-med' },
  tech: { id: 'tech', label: 'Tech', title: 'Digital skills and career readiness', anchor: 'programs-tech' },
} as const;

export type TrackId = keyof typeof tracks;
